include_guard(GLOBAL)

if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
    set(ZOO_PROJECT_IS_TOP_LEVEL ON)
else()
    set(ZOO_PROJECT_IS_TOP_LEVEL OFF)
endif()

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

option(ZOO_BUILD_TESTS "Build test suite" OFF)
option(ZOO_BUILD_INTEGRATION_TESTS "Build integration test suite" OFF)
option(ZOO_BUILD_EXAMPLES "Build examples" OFF)
option(ZOO_BUILD_BENCHMARKS "Build local performance harnesses" OFF)
option(ZOO_BUILD_DOCS "Build API documentation with Doxygen" OFF)
option(ZOO_ENABLE_COVERAGE "Enable coverage instrumentation" OFF)
option(ZOO_ENABLE_SANITIZERS "Enable ASan/TSan/UBSan" OFF)
option(ZOO_WARNINGS_AS_ERRORS "Treat warnings in zoo-owned targets as errors" OFF)
option(ZOO_ENABLE_INSTALL "Generate install and package metadata" ${ZOO_PROJECT_IS_TOP_LEVEL})
if(APPLE)
    option(ZOO_ENABLE_METAL "Enable Metal acceleration (macOS)" ON)
else()
    option(ZOO_ENABLE_METAL "Enable Metal acceleration (macOS)" OFF)
endif()
option(ZOO_ENABLE_CUDA "Enable CUDA acceleration" OFF)
option(ZOO_BUILD_HUB "Build the hub layer (GGUF inspection, HuggingFace, model store)" OFF)
option(ZOO_ENABLE_LOGGING "Enable debug logging to stderr" OFF)
set(ZOO_LLAMA_REPOSITORY "https://github.com/ggerganov/llama.cpp.git" CACHE STRING
    "llama.cpp repository used by FetchContent")
set(ZOO_LLAMA_TAG "5cbfb18075c95437e4ac7fb50e3baf88fe137a87" CACHE STRING
    "llama.cpp git tag or commit used by FetchContent")
set(ZOO_INTEGRATION_MODEL "" CACHE FILEPATH "Path to a GGUF model used by live integration smoke tests")
